version: "3.8"
services:
  db:
    image: postgres:15
    container_name: blockchain-db
    environment:
      POSTGRES_DB: blockchain_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: JustineRhey021
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: blockchain-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/blockchain_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: JustineRhey021
    depends_on:
      - db

volumes:
  postgres_data:
